# Generated by Django 3.2.6 on 2021-09-27 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_title', models.CharField(default='default_name', max_length=100)),
                ('description', models.TextField(default='default_description')),
                ('entry_price', models.FloatField(default=None)),
                ('bid', models.FloatField(default=None)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('hash', models.CharField(default=None, max_length=66, null=True)),
                ('txId', models.CharField(default=None, max_length=66, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_vendor', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
