# Generated by Django 3.2.6 on 2021-09-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid',
            field=models.FloatField(default=None, null=True),
        ),
    ]
