# Generated by Django 3.2.6 on 2021-09-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0002_alter_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
