# Generated by Django 3.2.6 on 2021-09-27 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_auction', '0003_alter_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_vendor', to='auth.user'),
        ),
    ]
