# Generated by Django 3.2.6 on 2021-10-04 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0004_alter_auction_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
