# Generated by Django 3.2.6 on 2021-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auction', '0006_alter_auction_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
